### ISSUE TITLE
[Questions] Which version CodeWarrior should I use?

### ISSUE THREAD

**Issue by rickyzhang82** [macssh/macssh#6]
Thanks for migrating from source forge. This saves me leg work to repeat the task.

I wonder if it is possible to build this program for M68K under PowerPC in Mac OS X 10.4 Tiger?

If possible, what version of Code Warrior I should use?

thanks in advance.

**Comment by rickyzhang82** [comment]
Found the answer in your wiki. Thanks!

**Comment by mrpippy** [comment]
Sorry I need to improve the documentation, yes I'm using CW Pro 8 on 10.4, and can build for PPC or 68k (with files copied from Pro 6).

Note that the `master` branch probably won't build correctly for 68k. I'm working in the `libssh2` branch, and had to fix the project files for 68k to build correctly (segments were mixed up, had to use some different libraries, etc.) `libssh2` is still under heavy development, but it's improving.

 Anything you're interested in doing with MacSSH?

**Comment by rickyzhang82** [comment]
Nothing special. I tried MacSSH binary in 68k Mac. It works after my tweaking modern ssh server configuration. So I'm curious how 68K mac networking works without using socket. 

Now I'm working on building it for 68k Mac. So what do you plan to do with it?

**Comment by mrpippy** [comment]
I've been replacing the old SSH implementation (lsh + libgcrypt from 2001) with libssh2 and mbed TLS, to support newer crypto algorithms and servers without any tweaking. They're also a lot simpler. I also want to fix bugs and add features if possible.
